"""Add room_alias table

Revision ID: add_room_alias_table
Revises: 882307784a69
Create Date: 2025-09-06 19:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_room_alias_table'
down_revision = '882307784a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_alias',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('room_name', sa.String(length=100), nullable=False),
        sa.Column('room_number', sa.Integer(), nullable=False),
        sa.Column('tournament_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], name='fk_room_alias_tournament'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_alias')
    # ### end Alembic commands ###
